### PR TITLE
Full logo

### PR DESCRIPTION
**Pull request by robertsbaer**
Made edits to make it responsive

### CODE REVIEW

**Comment by jserrao** [comment]
Screen Shot 2020-02-11 at 12 12 34 PM

@robertsbaer - get rid of the static left margin between the words. Baseline between modern / trousseau doesn't look inline - they are slightly different. A logo is too important to let that slip.

**Comment by robertsbaer** [comment]
@jmripper @jserrao Jenny said she fixed it.

**Comment by jserrao** [comment]
@jmripper - where is your fix?

**Comment by jmripper** [comment]
@robertsbaer @jserrao its on my homepage which isn't merged. just go add in align-items: baseline

**Comment by jserrao** [comment]
@jmripper + @robertsbaer - this took modification of the `line-height` on `.logo-word-trousseau` to get just right. This is a high profile, we want to be pixel perfect here.

```css
.logo-word-trousseau {
    font-family: Playfair display;
    font-style: italic;
    font-weight: bold;
    font-size: 24px;
    letter-spacing: 0.1px;
    color: #25282B;
    margin: 0 0 0 1%;
    line-height: 0.9;
}

@media only screen and (min-width: 600px) {

    .logo-word-trousseau {
        font-family: Playfair display;
        font-style: italic;
        font-weight: bold;
        font-size: 44px;
        letter-spacing: 0.1px;
        color: #25282B;
        margin: 0 0 0 1%;
        line-height: 0.85;
    }
}
```

Fix is merged into `develop` if you want to pull down.

**Pull request merged**
