### PR TITLE
Tagline

### PR DESCRIPTION
**Pull request by jmripper**
Issue #94 

It should be all good to go.

### CODE REVIEW

**Comment by erinkelley27** [comment]
@jmripper Fix merge conflict and then I will review!

**Comment by jmripper** [comment]
@erinkelley27  should be all good to go now!

**Comment by jmripper** [comment]
@erinkelley27 yep I can add it in

**Comment by erinkelley27** [comment]
@jmripper What is going on with the font here?

**Comment by jmripper** [comment]
@erinkelley27 Not sure I understand...I copied the exact front over from the mock and its pulling in the font Playfair Display from the CSS variable?

Screen Shot 2020-02-07 at 12 28 57 PM

Screen Shot 2020-02-07 at 12 30 42 PM

**Comment by erinkelley27** [comment]
Here's the mobile version. I think the subtitle needs to be Raleway.

Screen Shot 2020-02-07 at 12 32 37 PM

**Comment by jmripper** [comment]
@erinkelley27 that's super weird! This is what it looks like for me. 
Screen Shot 2020-02-07 at 1 03 31 PM

**Pull request merged**
