### PR TITLE
How we work

### PR DESCRIPTION
**Pull request by jmripper**
@erinkelley27 this should be all good to go, the only issue is I don't know how to change the color of the icons from front awesome without created a .css file.

### CODE REVIEW

**Comment by jmripper** [comment]
@erinkelley27 Oh it totally does for me too but it says its Playfair Display. Not sure what else to do?

**Comment by erinkelley27** [comment]
@jmripper Seems like something you may need to look into more, either with the CSS variables or the font imports.

**Comment by jmripper** [comment]
@erinkelley27 just asked john and we double-checked and its loading correctly as Playfair display, even changed it to use the CSS variable.

**Comment by erinkelley27** [comment]
@jmripper Looks like there are merge conflicts here.

**Pull request merged**
