### PR TITLE
#44 - gowns page

### PR DESCRIPTION
**Pull request by mdrisco4**
I know there are going to be a few adjustments needed, but I will need a bit of direction on the changes on which I should work.  I know links are not in place, but most of those pages are not built yet so I am not sure where everything is going, click-event wise.  Also, b/c of the ambiguity in the dimensions of the mockup vs. what will be used in real world application I got to a reasonable approximation of what it looks like we are trying to do and need some feedback...with the NavMenu and SearchMenu in particular: (lines 153-161).  SearchMenu is responsive, while NavMenu is not, staying more fixed with regards to the logo, lmk what you think.  Additionally, the background color.  the mockup looks white, but click on the mockup and the color listed is the 'backgroundGray' color (as designated in the global styled components file found in the styles folder), this is of course a very simple adjustment if needed.  With the responsiveness I tried to find an easy medium regarding image warping/size differences, if you think it is necessary I could invoke some more breakpoints.  I had to make a handful of changes to some of the components, leaving a note in the NavMenu.storybook file and trying to take into account other uses around the project for others.

### CODE REVIEW

**Comment by jserrao** [comment]
@mdrisco4 - really impressive PR. This is technically in Sprint 2, just addressing Sprint 1 stuff this morning. I will not merge this in until at the earliest 3-4p today.

**Comment by mdrisco4** [comment]
Ok.  Sounds good.  We are doing Outcomes now but I certainly would like to keep getting things done.  While you are still working on Sprint1 lmk what else I can be tackling...I am happy to pick up another page, but unsure since I am not sure how many edits will be coming back.  lmk what you think is best.

**Comment by jserrao** [comment]
@mdrisco4 appreciate the effort. We need to check-in as a team though. 
Work with Jenny on component refactoring if you can. She has style needs.

**Comment by jmripper** [comment]
@mdrisco4 When you view this page on mobile with a screen size smaller then 340px which is iphone 5/SE there is this white space to the right, somewhere the width that is declared is larger then 340 and can't go smaller.
Screen Shot 2020-02-11 at 2 27 44 PM

**Comment by jmripper** [comment]
@mdrisco4 would also add in a bit more spacing above the gowns button filter up top. so between the nav and button. maybe make it 20px or 25px?

**Comment by mdrisco4** [comment]
@jmripper noted.  I will get back to this when I am done refactoring this component.  that shouldn't be too hard to remedy.  I will def want you to take a second look at my refactor...like I said, the midsize is...messy...mobile is solid and desktop will be when I am done.

**Comment by jmripper** [comment]
@mdrisco4 take out the arrows since I don't think we are doing sliders but that is @jserrao call.

Would line the fall 2020 collection text up with the edge of the first image like it is in the mock, 
Screen Shot 2020-02-11 at 2 37 26 PM

**Comment by jmripper** [comment]
@mdrisco4 could you update the names of the correct dresses to the correct collection year? they all say luca or vida

**Comment by jmripper** [comment]
@mdrisco4 for tablet and up I could limit the padding-top to 25px or 30px, 80 is just a little much and get ride of the hight on that element, it's not needed.

**Comment by mdrisco4** [comment]
@jmripper I am pretty sure that part is sliders.  In the mobile version it is one page with sliders and in the desktop there are several pages each with its own static images.  just being populated with one single mockData array with 8 dress pics and names, what goes in the sliders now doesn't matter...would just have to make new mockData arrays that will probably got tossed or moved anyway.  I will get to all these adjustments shortly.

**Comment by jmripper** [comment]
@mdrisco4 for desktop you have a random hr line right above fall 2020 collection that you don't need.

**Comment by jserrao** [comment]
@jmripper & @mdrisco4 teamwork making this happen, nice.

**Comment by jmripper** [comment]
@mdrisco4 for your search menu container, don't use border-top to add spacing, use margin-top or padding-top, border should just be used for border elements.

**Comment by jserrao** [comment]
@mdrisco4 - Jenny's code review is solid. You still did great work on this. You can light her up and review her Homepage whenever she submits it.

**Comment by mdrisco4** [comment]
@jserrao lol.  we have been working in tandem on this and the bride-review refactor.  I am going to work on the notes she provided here while she is helping look over the bride-review and I can continue work on either or both this evening.  I don't think her edits here will be too time consuming b/c I am familiar with the components that take up most of the page b/c those were issues I did.

**Comment by mdrisco4** [comment]
@jserrao I want to think about having images formatted to minimize warping issues with different sizes.  Changed image HxW to %s from PXs for now.  can approach that again later when we are passing data to/from BE.

**Comment by jserrao** [comment]
@mdrisco4 - what are you doing in `gatsby-config.js`? That's going to break a lot of stuff...

**Comment by mdrisco4** [comment]
@jserrao A whole bunch of stuff broke when I pulled down changes from Develop.  I tried npm rebuild, npm install, removed node_nodules and did npm install, etc....all I did was copy paste the contents, which had changed w/o me touching them for some reason, from a previous commit where everything was running fine to try and stop throwing errors from that file.  Seems to have worked on the two branches I am bouncing back and forth between.

**Comment by jserrao** [comment]
@mdrisco4 - copy/paste current `gatsby-config.js` and `package.json` from `develop` into your `44-gown-page` branch. See if you can get them to work.

Again, I can get creative like I did yesterday solving a lot of these challenge for everyone, but in the real world this code will get sent back to you. Try to resolve it yourself. If you want to jump out of a window, partially that's good - you'll be sure you don't do this again. But also partially bad, because I like you and want you to succeed. If you dont get it by lunch, I'll come help you this afternoon - fair? ;)

**Comment by mdrisco4** [comment]
@jserrao What I meant by the previous comment was that I did fix it.  everything works.  its all good.  I asked Erin about it briefly, nut otherwise I had taken it upon myself to make it work b/c I know that  is how it will go when I am actually gainfully employed.  Just pulled develop changes again to make sure.  Everything is running smoothly.

**Pull request merged**
