### PR TITLE
Gowns header

### PR DESCRIPTION
**Pull request by AGarcia85**
created something needs more css finess

### CODE REVIEW

**Comment by erinkelley27** [comment]
@AGarcia85 Let me know when the you have implemented the CSS finesse, and I'll review.

**Comment by AGarcia85** [comment]
@erinkelley27  touched up css got it close to what component should look like.

**Comment by jserrao** [comment]
@AGarcia85 did this? Good thing the dictator let the guns cool for a minute and brought his styling A game.

**Comment by AGarcia85** [comment]
@jserrao  Every now and then a dictator has to appease his people with simple gestures of good intentions 😉

**Pull request merged**
